### ISSUE TITLE
API call should use two letter abbr instead of full country name

### ISSUE THREAD

**Issue by leroybryant** [USStateDept/FPA_Core#110]

**Comment by KWhyms** [comment]
@wiseguy - Do we have any examples of an API call to use?

**Comment by KWhyms** [comment]
I've found a solution for this... I'm just testing it to make sure I haven't messed anything up.

**Comment by KWhyms** [comment]
UPDATE:  After some testing it appears that I have slightly broken it in making my changes (on my machine only).  My changes make it so that only the 2 letter abbreviation appears in the URL.  The problem is that it seems to work fine for bar graphs, but line graphs will not render.
