### ISSUE TITLE
Ascii data load error for human dev index (formerly API Calls bombing out)

### ISSUE THREAD

**Issue by leroybryant** [USStateDept/FPA_Core#114]
http://localhost:5000/api/slicer/cube/geometry/cubes_aggregate?cubes=human_development_index&drilldown=geometry__time&cut=geometry__time:1990-2014&order=time

AttributeError: 'NoneType' object has no attribute 'table'

**Comment by brodydittemore** [comment]
Indicator not fully loaded - fails when creating OR project.

**Comment by nathanhilbert** [comment]
It was an ascii error.  See https://github.com/USStateDept/FPA_Core/commit/e819cf84f4d31e10074f7faf5b9c912d9653c7ba
