### ISSUE TITLE
Update map with geography selected

### ISSUE THREAD

**Issue by wiseguy** [USStateDept/FPA_Core#124]

**Comment by dstepp** [comment]
Which map are we talking about? The one on the Countries page?

**Comment by wiseguy** [comment]
The Build a Visualization page, countries tab. 

The countries page will take you directly to the data visualization in one click so no need for map update

**Comment by ghost** [comment]
Two step process:
1. Un-highlight country on map when country is deselected in list
2. Enable highlighting when clicking on country inside of map

**Comment by dstepp** [comment]
@bshporkin is this related to #228 and #227?

**Comment by ghost** [comment]
Refactored in issues 226, 227, and 228.
Close in github
