### ISSUE TITLE
Share Url by shortening

### ISSUE THREAD

**Issue by wiseguy** [USStateDept/FPA_Core#126]

**Comment by dstepp** [comment]
Needs testing with find.stat.gov

**Comment by aminvafa** [comment]
I tested a handful, and it seems to work fine. Would be nice if the window that popped up with the URL would have a "copy to clipboard" button (or would automatically copy to your clipboard).

**Comment by aminvafa** [comment]
The twitter button next to the share URL button doesn't work.
