### ISSUE TITLE
As a user, I would like the 500 error resolved when logging in.

### ISSUE THREAD

**Issue by dstepp** [USStateDept/FPA_Core#133]
When logging in from the /login/ page, I recevied a 500 error:

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by dstepp** [comment]
It appears that the Login now requires an email address. I cannot recreate this bug with out standard login and password. Will need to test with email/password.

**Comment by nathanhilbert** [comment]
@brandheisey mind if I look at this?

**Comment by brandtheisey** [comment]
@nathanhilbert Go for it. I've been unable to reproduce it so maybe a more FIND experienced set of eyes will see it.

**Comment by dstepp** [comment]
See my comment. Might be able to close this out. I got it previously using the standard login information. Not with the new email address. This page could be cleaned up regardless but that would be another issue.

**Comment by nathanhilbert** [comment]
Maybe change to: as a user I don't want to see a 500 error if I enter
incorrect information.  Or give me something more reassuring than a 500
error.
Either way, I'll take a look at it.

**Comment by nathanhilbert** [comment]
The probelm was that the csrf_token was regenerated if the form submit failed.  The app would expect the original csrf_token.  If csrf_token available in current form, then use that, if not available generate a new one.
