### ISSUE TITLE
API Call to get data at Region Level

### ISSUE THREAD

**Issue by wiseguy** [USStateDept/FPA_Core#136]
Trying to get Data at EUR region level. But it gives me individual countries at that level.

http://localhost:5000/api/slicer/cube/geometry/cubes_aggregate?cubes=gdp_per_capita&cut=geometry__time:1990-2014&order=time&drilldown=geometry__country_level0@dos_region|geometry__time&cut=geometry__country_level0@dos_region:EUR

If I pass two region names (EUR and SCA) then it does what I expected.

http://localhost:5000/api/slicer/cube/geometry/cubes_aggregate?cubes=gdp_per_capita&cut=geometry__time:1990-2014&order=time&drilldown=geometry__country_level0@dos_region|geometry__time&cut=geometry__country_level0@dos_region:EUR;SCA

**Comment by leroybryant** [comment]
KWhyms found a solution removing @dos_region
