### ISSUE TITLE
API call to get Regions from Multiple Groups

### ISSUE THREAD

**Issue by wiseguy** [USStateDept/FPA_Core#137]
In this example I have selected groups DoS and DoD and their regions USCENTCOM, USSOUTHCOM, EUR, and SCA.

Looks like some regions are missing.

http://localhost:5000/api/slicer/cube/geometry/cubes_aggregate?cubes=gdp_per_capita&drilldown=geometry__country_level0@dod_cmd|geometry__time&drilldown=geometry__country_level0@dos_region|geometry__time&format=json&cut=geometry__time:1990-2014&order=time&cut=geometry__country_level0@dod_cmd:USCENTCOM;USSOUTHCOM&cut=geometry__country_level0@dos_region:EUR;SCA

**Comment by KWhyms** [comment]
@wiseguy - Brody and I ran some tests and it appears that the call you wrote will return intersections between the sets you request when attempting to make calls to multiple sets.  This is why the data appears to be "missing".

We ran a query using that call for two sets that we know will not intersect and it returned 0 results.

When I ran the call minus the cuts it showed all of the regions for both like we saw before with two regions / result--one from DoS and one from DoD.

I counted the number of cells that contained both SCA and USCENTCOM and the number exactly matched the number of cells returned in your example.

Based on our findings, it appears that this would be be handled by making separate calls.  

I will await your response before closing this one out.

**Comment by dstepp** [comment]
What library are we using again?

**Comment by leroybryant** [comment]
http://cubes.databrewery.org/
https://github.com/DataBrewery/cubes

**Comment by dstepp** [comment]
Thanks! Do you think we should open an issue on their github? It looks like the contributors are responsive.

**Comment by leroybryant** [comment]
I'll defer to @KWhyms  and @brodydittemore  .  They've been looking at this the most.

**Comment by KWhyms** [comment]
Based on conversations I had with Brody earlier it seems as though it may be possible to send it as multiple commands and append the JSON responses, but I'm not 100% sure on that just yet.

**Comment by dstepp** [comment]
Okay, I just asked the developers: https://github.com/DataBrewery/cubes/issues/316

**Comment by nathanhilbert** [comment]
I mentioned to @dstepp that we are working on the downstream project from the cubes repo.  It is located here https://github.com/USStateDept/cubes and referenced here https://github.com/USStateDept/FPA_Core/blob/master/requirements.txt#L34. I think it has something to do the hierarchy logic here https://github.com/USStateDept/cubes/blob/7b003b5500800463bd1fe4c47e52df75026e2c5f/cubes/browser.py
Feel free to assign to me.  There might be some potential to easily refactor this code with the recently updated vanilla cubes https://github.com/DataBrewery/cubes/releases v1.0.1 (we forked from v1.0)

**Comment by KWhyms** [comment]
You think that what has to do with the hierarchy logic there?  Is what I found true or not?  Is this the expected functionality or not?  I'd like to know this before moving forward with trying to "fix" anything.  It makes no sense to just assume.  Perhaps it's supposed to return intersection when written the way it is.  If that's the case, would we not run the risk of actually REMOVING functionality?  Does it or does it not makes sense to run this as separate calls?  Has anyone found an answer to these questions?

**Comment by dstepp** [comment]
Kelvin, I spoke with Nathan. Let's go with Aamirs suggestion to union the separate calls. It sounds like there are problems with the source code on sending multiple regions in the same API call.

**Comment by KWhyms** [comment]
Sounds like a plan.
