### ISSUE TITLE
API call to get countries at Region Level

### ISSUE THREAD

**Issue by wiseguy** [USStateDept/FPA_Core#139]
This is the converse of #136.

Trying to get Countries at EUR region level. This works as expected.

http://localhost:5000/api/slicer/cube/geometry/cubes_aggregate?cubes=gdp_per_capita&cut=geometry__time:1990-2014&order=time&drilldown=geometry__country_level0@dos_region|geometry__time&cut=geometry__country_level0@dos_region:EUR

But If I pass two region names (EUR and SCA) then it does not work. 

http://localhost:5000/api/slicer/cube/geometry/cubes_aggregate?cubes=gdp_per_capita&cut=geometry__time:1990-2014&order=time&drilldown=geometry__country_level0@dos_region|geometry__time&cut=geometry__country_level0@dos_region:EUR;SCA

**Comment by KWhyms** [comment]
I looked at these commands and they're the exact same as the ones in issue #136.  How does it work both ways?  Am I missing something?

**Comment by leroybryant** [comment]
@KWhyms , he needs countries on the bottom one in this one.  He needs countries on the top one in #136.  He needs regions on the top one in #136 and regions on the bottom one in this.  Something happens when more than one region is added.

**Comment by KWhyms** [comment]
Ahh I see... Okay.  I have been reading the Cubes documentation and I think I may have found something that might help.  Once I finish setting up my virtual box here at home I should be able to test a few ideas.

**Comment by KWhyms** [comment]
Okay so one more question.  Being that the commands in both 136 and 139 are exactly the same but we expect opposite functionality, can it be assumed that for individual countries we wish to use the following command:

http://localhost:5000/api/slicer/cube/geometry/cubes_aggregate?cubes=gdp_per_capita&cut=geometry__time:1990-2014&order=time&drilldown=geometry__country_level0@dos_region|geometry__time&cut=geometry__country_level0@dos_region:EUR ?

(Multiple countries would be appended using semicolons like in the example that currently does not work)

And if that is the case, what is the command that we would expect to return regions? I know these are a lot of questions, but when the commands are identical it's difficult to get a handle on what we actually want it to do. 

We saw yesterday that a semicolon seemed to be enough to change the behavior (although it probably shouldn't have) but that can't be the only difference between the two commands.  

Hopefully that question makes sense.

**Comment by wiseguy** [comment]
I guess the important thing is there should be a way to say that I want EUR level data or the countries in EUR. Now that should be expanded to support multiple regions. For example EUR and SCA. It doesn't matter what the structure of the api call.

**Comment by KWhyms** [comment]
Countries...

Does this command work for everyone?  This works for both single values and multiple values for me.

http://finddev.edip-maps.net/api/slicer/cube/geometry/cubes_aggregate?cubes=gdp_per_capita&cut=geometry__time:1990-2014&order=time&drilldown=geometry__country_level0|geometry__time&cut=geometry__country_level0@dos_region:EUR;SCA

**Comment by leroybryant** [comment]
KWhyms found a solution removing @dos_region
