### ISSUE TITLE
As a user, I should be able to save visualizations

### ISSUE THREAD

**Issue by brandtheisey** [USStateDept/FPA_Core#141]
As discussed in the 7/8 meeting.

Initially, this should mean the able to click a "Save this visualization" link on the side of a page and it will auto save to the user profile.

This requires:
- [x] ~~User Profile link in the navigation menu~~
- [x] ~~User profile page (template)~~
- [x] ~~User profile route~~
- [x] ~~API/route that can save a visualization~~
- [x] ~~API/route that can delete a visualization~~
- [x] ~~Investigate why dataview was set to have a 1 to 1 relationship with account~~
- [x] ~~User profile visualization management UI fragment~~

**Comment by leroybryant** [comment]
Some pertinent parts of the codebase:
openspending/views/api_v2/dataview.py
openspending/model/dataview.py

**Comment by dstepp** [comment]
Requirement number 33 - "FIND will allow USG users to save visualizations which can be made available publicly."  Do we need a second issue for the "made publicaly" part?

**Comment by dstepp** [comment]
I'm closing #181 because it's part of this.

**Comment by brandtheisey** [comment]
Pushed into master. Other people will need to test to verify it works as expected.
