### ISSUE TITLE
Dataview has a probably inccorrect 1 to 1 relationship with Account

### ISSUE THREAD

**Issue by brandtheisey** [USStateDept/FPA_Core#153]
Dataview has a 1 to 1 relationship with Account.

Since Dataview is the table where we intend to save visualization urls, and any given user can have more than 1 saved visualization, this seems like an oversight. Further, the behavior of flask / sqlalchemy / postgres causes a new insert by the same user to silently update the previous saved dataview to have no  associated account_id while saving the new row as expected.

This appears to be fixable by changing this line in **model\dataview.py** 

```
account = relationship(Account, backref=backref("dataviews", uselist=False))
```

to

```
account = relationship(Account, backref=backref("dataviews"))
```

This change allows multiple inserts by a given user to behave as expected and doesn't appear to require a db change as the current constraint definition for that Foreign Key doesn't prevent my desired behavior:

```
  ADD CONSTRAINT dataview_account_id_fkey FOREIGN KEY (account_id)
      REFERENCES account (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;
```

ie, after changing the model file, i get the desired behavior without changing the FK constraint at the database level.

If anyone has any thoughts on this, please respond below.

**Comment by dstepp** [comment]
@nathanhilbert please review and confirm.

**Comment by nathanhilbert** [comment]
yup, dataview to account should be a many-to-one.  Removing uselist=False does fix this.  And, you're right that there is no need to change the database, this is python code before it hits the backend.
I suggest you move the relationship over to the account model for readability, but not a big deal.

**Comment by dstepp** [comment]
Is this closed?
