### ISSUE TITLE
Add ability to export data table from visualization menu

### ISSUE THREAD

**Issue by brodydittemore** [USStateDept/FPA_Core#167]
As CSV, XLS, or JSON, with options for wideform or longform.

**Comment by brodydittemore** [comment]
Export should also include all regional options for a country (France: EUR, Europe, etc.)

**Comment by brodydittemore** [comment]
Wideform sort: Country A-Z
Longform sort: Year (ascending), Country (A-Z)

**Comment by fucc1** [comment]
As a user, I would like to have the data be downloadable in XLS/CSV in wide instead of long format (+ metadata in the download file)
