### ISSUE TITLE
Style the login page

### ISSUE THREAD

**Issue by nathanhilbert** [USStateDept/FPA_Core#177]

**Comment by dstepp** [comment]
Need to create content and mockup.

**Comment by brandtheisey** [comment]
Who can I reach out to get an idea of what this should look like?

**Comment by wiseguy** [comment]
There is no design as such for any of the pages. As long as it has a consistent feel then we are good. Bootstrap classes will help.

**Comment by brandtheisey** [comment]
Closed by #214

**Comment by nathanhilbert** [comment]
Login looks good. Thanks for cleaning that up.
