### ISSUE TITLE
Icon for Visualization Save

### ISSUE THREAD

**Issue by brandtheisey** [USStateDept/FPA_Core#181]
Where do the Twitter and Share Icons come from on the visualization page?

![screen shot 2015-07-17 at 8 46 37 am](https://cloud.githubusercontent.com/assets/7915386/8747380/5ffd1cfe-2c60-11e5-96dd-dd20c591390f.png)

I'd like to add the save visualization link as a icon after the share icon but I'd like to use something from the same library.

**Comment by wiseguy** [comment]
I am using www.thenounproject.com . This is a great resource. It is not free but has an immense collection of user contributed icons. I used glip to resize the file.

**Comment by dstepp** [comment]
In support of requirement 33.
