### ISSUE TITLE
As a registered user, I would like a forum with limited functionality.

### ISSUE THREAD

**Issue by dstepp** [USStateDept/FPA_Core#184]
Registered users should be able to navigate to a forum, create topics and have discussions. We can find an open source forum module to integrate. @nathanhilbert would this be something you're comfortable working on over the next 2 weeks prior to delivery?

Requirement number 67.

**Comment by nathanhilbert** [comment]
Yes, I can work on this.  Maybe we can discuss a bit further.  My suggestion is that there should be context around the discussion (e.g. the discussion should form around the indicator/SPSD category/data visualization).  The other option is to do a separate module or page that just has the forum and is not tied to any of the web entities.

**Comment by dstepp** [comment]
Yes, let's talk about this before we get started. From reading the requirements, it looks like we just want to show some basic functionality. The latter option (separate module) seems like the easier lift. The users could then tie the discussion back to the indicators using the shorten urls?

**Comment by nathanhilbert** [comment]
closed with #215
