### ISSUE TITLE
As a user, I would like Map as a visualization.

### ISSUE THREAD

**Issue by dstepp** [USStateDept/FPA_Core#187]
Using OpenStreetMaps, Leaflet, and/or another mapping method, the FIND project should be able to display information by country on a map.

**Comment by jonvan5** [comment]
Is this different from #183 or are they redundant? It seems there are several ways this can be done-- using the tools you mentioned, but highcharts might also be an option.

**Comment by leroybryant** [comment]
My assumption is this one is getting the map minimally functional for the beta and the other is the more fleshed out one after getting beta feedback.  I was going to use Leaflet since the GIS team has experience with that and that is the stub map viewable now is based on that.

**Comment by jonvan5** [comment]
That should be fine, so long as the minimal functionality includes having data displayed as colors (e.g. http://leafletjs.com/examples/choropleth.html).

**Comment by leroybryant** [comment]
Breaking out into #254, #255, #256, and #257
