### ISSUE TITLE
Standardize CDA indicator names

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#188]
Currently, there are ~60 indicators whose label includes the phrase "[MCP Scaling]" or "[CDA Scaling]". We would like to keep the indicator names but change that bracketed label to "[CDA 1-5 Scaled]". We were told you could do a batch change so that we wouldn't have to do them one by one.

**Comment by leroybryant** [comment]
I'll do this.

**Comment by leroybryant** [comment]
@aminvafa They should all be [CDA 1-5 Scaled] now.

**Comment by aminvafa** [comment]
@leroybryant looks good. thanks!
