### ISSUE TITLE
Remove Data Story Sliders from home page

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#193]
Remove widget from home page with rotating data story thumbnails and text.

**Comment by dstepp** [comment]
This was closed for some reason.

**Comment by dstepp** [comment]
![capture](https://cloud.githubusercontent.com/assets/5739648/9121874/37efdb0e-3c53-11e5-9ae8-b2aa30a4c06c.PNG)

**Comment by dstepp** [comment]
Remove those.
