### ISSUE TITLE
Data "Collections" should align to F specifications

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#196]
Currently, "Collections" corresponds to all sources. F identified limited collections for display. If needed, F can help tag specific indicators to each collection.

**Comment by fucc1** [comment]
Per our discussion earlier today(8/3/15), here is the list of our Collections (Also include the spelled out acronyms).  Please ensure that these are integrated in as part of the new collections category.

• MCC – Millennium Challenge Corporation
• CDA – Country Data Analytics 
• DHS – Demographic and Health Surveys 
• SDGs  - Sustainable Development Goals
o   This will have zero as the little bubble number in the top right corner for now, this is fine.  
• UIS  - UNISCO Institute of Statistics
• WHO – World Health Organization 
• International Monetary Fund (IMF) World Economic Outlook

**Comment by aminvafa** [comment]
Use this for data collection icon
http://www.flaticon.com/free-icon/cabinet-with-three-drawers_1209

**Comment by aminvafa** [comment]
Use this for data collection icon: 
http://fortawesome.github.io/Font-Awesome/icon/cubes/

In #200, ignore icon for data collection. But still use the humanitarian assistance icon, as per foreignassistance.gov.

**Comment by leroybryant** [comment]
The ones that have no indicators won't be visible until an indicator is associated.  It won't say 0.  It just won't be visible.
