### ISSUE TITLE
Update Icons

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#200]
Update Humanitarian Assistance icon from: 
![image](https://cloud.githubusercontent.com/assets/10505111/8858636/7e8573d4-3146-11e5-8188-c76b9e2d8ef8.png)
to
![image](https://cloud.githubusercontent.com/assets/10505111/8858644/856f4a76-3146-11e5-8696-17aa33dbdd8a.png)

Update "Collection" icons from:
![image](https://cloud.githubusercontent.com/assets/10505111/8858644/856f4a76-3146-11e5-8696-17aa33dbdd8a.png)
to
![image](https://cloud.githubusercontent.com/assets/10505111/8858658/a4517590-3146-11e5-8260-1dda933cccc0.png)

Change icon for "Treemaps" to an actual treemap icon instead of a dendrogram

**Comment by dstepp** [comment]
@aminvafa where are these icons from? We'd like to use the same collection for all the icons - possibly http://fortawesome.github.io/Font-Awesome/icons/

**Comment by ghost** [comment]
What is the difference between a dendrogram and a treemap?

**Comment by aminvafa** [comment]
so i'm not the only one tricked by the latin root "dendro!"

here's an example what we want for treemap: http://media.tumblr.com/e524c3db5276550ae3372539a513911d/tumblr_inline_mggvf6Qosa1ql3h8n.jpg

here's an example of a dendrogram: http://i.stack.imgur.com/JWbMJ.jpg

**Comment by ghost** [comment]
Can someone explain what the "content '\e6xx'" references mean in the visualization.styl file?

Also, if we're switching from Noun to Font-Awesome, which icons should be used In place of the ones mentioned? Does someone need to formally decide on this or do we just chalk it up to artistic license?

**Comment by ghost** [comment]
In which file are the collections icons set?
