### ISSUE TITLE
Change "Environment" from sub-category to category

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#201]
Currently "Environment" is a sub-category within one of the SPSD sectors. We would like it elevated to a category, with an icon that corresponds to the Environment Icon on ForeignAssistance.gov http://beta.foreignassistance.gov/#explore

**Comment by nathanhilbert** [comment]
The changes weren't saving before.  They work with https://github.com/USStateDept/FPA_Core/commit/9d696ba27578955852ed783c4a39b612b9e0b908.  Waiting for the code to be entered into the server in order to change.  Icon is already in the system.

**Comment by nathanhilbert** [comment]
Updated production database to move environment to spsd and cleared the cache.
