### ISSUE TITLE
Edit Country Group and Region Text

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#203]
-Change “Country Groups” to “Country Groupings”
-Within the ”Country Groupings” pull down, change “World Bank” to “Income Groups”
- (See below) When users select a Country Grouping, please change the “Regions” box to say “Groupings” instead

![image](https://cloud.githubusercontent.com/assets/10505111/8858937/6407235c-3148-11e5-9a3c-7639bf0dc87f.png)

**Comment by leroybryant** [comment]
Do you still have that those dropdowns? I'm not seeing them.

**Comment by brandtheisey** [comment]
The current country page looks like this:
![screen shot 2015-08-10 at 3 36 54 pm](https://cloud.githubusercontent.com/assets/7915386/9181903/7f42363a-3f75-11e5-8116-ceea50e2b120.png)

Does it still need to be be changed?

**Comment by aminvafa** [comment]
Everything here is good. The only change that needs to be made is "World Bank" still needs to be changed to "Income Groups." After that, it's all set.

**Comment by ghost** [comment]
It's just the label that needs to be changed in the dropdown, or the href as well?
