### ISSUE TITLE
As a user, I would like to plot the Global Average

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#205]
Currently, Global Average/Min/Mix are available alongside other queries when you get to the viz. I would like to select "Global Average" from the country/region selection page and have it be my primary geography.

**Comment by aminvafa** [comment]
I just noticed that this feature exists, but possibly not intentionally. Currently, if you go through build-a-viz WITHOUT selecting a country (as in, you only pick indicators and chart type), then the default chart has global min/max/avg. It seems like a possible solution to #205 would be just to inform the user that Global is the default if no geo is selected, and when you get to the viz, make the default (for only this situation) to show (instead of default hide) the global min/max/avg points.

**Comment by dstepp** [comment]
Add the following text to the Countries page of Build a Visualization, "Global Min/Max/Avg is the Default"
