### ISSUE TITLE
Significant digits in data labels

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#206]
Reduce to two digits after decimal

**Comment by ghost** [comment]
Which data labels are you talking about?

**Comment by aminvafa** [comment]
basically, when you hover over any visualization with non-integer data, it should only go to two decimal places.

for example: if GDP per capita of, say, Uganda is $123.4567890123, the data label shouldn't display all the places after the decimal as it does now. It should jsut say $123.46.
