### ISSUE TITLE
QA check: adjust chart axes

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#207]
QA check: if visualization has all positive values, chart shouldn't go below zero

**Comment by aminvafa** [comment]
-If visualization has all positive values, chart shouldn't go below zero
-All CDA charts should have 1-5 scale
-F can provide more specificity

**Comment by dstepp** [comment]
Do you have an example chart that doesn't fit this criteria?

**Comment by aminvafa** [comment]
CDA should actually be 0-5 (all values should be 1-5). Here are 2 visualizations that have different scales, and both scales should be 0-5.

http://finddev.edip-maps.net/data-visualization#f=1990|2014&i=gdp_per_capita_ppp_mcp_scaling&c=line&r=dos_region:SCA:all

http://finddev.edip-maps.net/data-visualization#f=1990|2014&i=control_of_corruption_mcp_scal&c=line&r=dos_region:NEA:all

**Comment by sc0ttius** [comment]
In your second example, Iraq has negative values in the data table. Consequently, the chart goes below zero. In this case are the data wrong? What is your expected result when the data reflects negative numbers? At this time, the chart automatically adjusts based on the highest and lowest point values.

**Comment by aminvafa** [comment]
so for all CDA data, it should always go from 1-5. this data needs to be reloaded. 

there are different cases where negative data are appropriate for a given dataset. it happens to not be appropriate for this particular dataset, but it may be for others.

if a dataset has all positive values, then the x-axis should always cross at 0. if there are negative values in the dataset, then i assume we can autoscale it.
