### ISSUE TITLE
Remove "highcharts.com" watermark

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#208]
Can “Highcharts.com” be removed from the graphs (and instead replaced with “FIND.state.gov”)?

**Comment by dstepp** [comment]
@aminvafa Our team needs to review the licensing for highcharts prior to modifying the watermark.

**Comment by dstepp** [comment]
This is done, but we need to purchase the license prior to implementing.

**Comment by dstepp** [comment]
OBE. The long term plan is to move from Highcharts to D3. The two main reasons, we need to refactor the util.js regardless, and D3 has greater support. And D3 is free while Highcharts is not.
