### ISSUE TITLE
As a user, I would like to search to work on the "Countries" page.

### ISSUE THREAD

**Issue by dstepp** [USStateDept/FPA_Core#212]

**Comment by KWhyms** [comment]
Can someone provide an example of what they mean for this one?

**Comment by brandtheisey** [comment]
The countries tab in the main portion of the app appears to be the same as the country portion of the data visualization portion of the app, but the countries tab produces no results (no discernable anything) when you do a search. Whereas in the visualization portion the doing a search produces something like this 
![screen shot 2015-07-28 at 1 22 59 pm](https://cloud.githubusercontent.com/assets/7915386/8938296/d405426a-352b-11e5-8b85-6d0d7976e1e7.png)

**Comment by dstepp** [comment]
This may be OBE. I'm waiting on a response back from F to see if we can just remove that section.

**Comment by aminvafa** [comment]
OBE. Let's just hide the search bar and we will redesign canned reporting under the new "Explore" tab.

**Comment by sc0ttius** [comment]
Search now works in the latest dev build. It was a quick adjustment rather than hiding it.
