### ISSUE TITLE
Bar graph: Can only do a max of 6 geos

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#219]
Bar graphs cannot graph more than 6 bars at a time. If a region is selected and all countries are plotted, only the last 6 countries show up. All selected geos should show up. See http://finddev.edip-maps.net/data-visualization#f=1990|2014&i=gdp_per_capita_ppp&c=bar&r=dos_region:AF:all

**Comment by brandtheisey** [comment]
Fixed as of 8/7
