### ISSUE TITLE
As a developer, I would like the unused code cleaned up

### ISSUE THREAD

**Issue by nathanhilbert** [USStateDept/FPA_Core#237]
Most of the management section is not needed in the forums module.  There are a few other places particularly https://github.com/USStateDept/FPA_Core/tree/master/openspending/templates

**Comment by dstepp** [comment]
Does this effect minimum functionality? If it does, let's look at it for the Closed Beta (mid-September), if not push to Production (October).

**Comment by nathanhilbert** [comment]
Will be closed with #340
