### ISSUE TITLE
Update the data stories on the home page

### ISSUE THREAD

**Issue by fucc1** [USStateDept/FPA_Core#240]

**Comment by brandtheisey** [comment]
#193 appears to be asking for Data Stories to be removed from the home page, can you clarify which should be done?

Also, can you provide some detail so we know what you are expecting to happen?

**Comment by fucc1** [comment]
We still want the Data Stories sliders to be removed.  We  would like to have the data stories on the bottom right of the home page be updated so that as a user, i can click on each data story and be taken to a separate website with the text and graphic (F will provide).   The preference is to have the graphic be interactable if possible, but if not, we can make it as a static downloadable image.

**Comment by dstepp** [comment]
I can fill in Brant based on our monday discussions. Do you have the data stories completed that you want to promote? I thought I saw an email about this a while ago but search didn't turn up anything.

**Comment by jonvan5** [comment]
I'll forward you the email, Dave.
