### ISSUE TITLE
Update Visualization when comparator(s) added - part 2

### ISSUE THREAD

**Issue by fucc1** [USStateDept/FPA_Core#241]
As a user, I would like to be able to do more advanced comparability across the other visualizations as well.  For example, I should be able to change one an indicator within a bubble chart that will automatically scale and re-size with the appropriate data.

**Comment by backnotprop** [comment]
Ill start this by being able to change the chart-type on the fly

**Comment by backnotprop** [comment]
@dstepp isnt the first part of this ticket (changing indicators) already accomplished by the "Edit Visualization" modal ?

**Comment by dstepp** [comment]
Seems so. Close.

**Comment by mdramos** [comment]
Will close after I add in a dropdown chart allowing change of chart-type
