### ISSUE TITLE
As a user, I don't want to see the API link if there is no information.

### ISSUE THREAD

**Issue by dstepp** [USStateDept/FPA_Core#244]
Remove the API link on the header until we have information about an actual API. Which would require us building an API first.

**Comment by brandtheisey** [comment]
In this case, I'll just comment out the link and leave the route because we intend to build an API.

**Comment by nathanhilbert** [comment]
If we want to provide an API builder to the user such as what I started here https://github.com/USStateDept/cubes_dataviewer (see live version at http://finddev.edip-maps.net/static/dataviewer/build/index.html)  or what has been worked on here https://github.com/spendb/babbage.ui, this would be the place.

**Comment by dstepp** [comment]
Just remove the link for now. Building the API is far in the future.
