### ISSUE TITLE
Forum / 'Who is online?' returns Internal Server Error

### ISSUE THREAD

**Issue by dstepp** [USStateDept/FPA_Core#246]
Signed in as admin@state.gov. Click on Board Statistics [Who is online?](http://finddev.edip-maps.net/forum/who-is-online) and return server error.

**Comment by nathanhilbert** [comment]
This feature requires a working redis server, which I wanted to avoid.  Can I just remove the link?

**Comment by dstepp** [comment]
Yeah, just remove it.

**Comment by nathanhilbert** [comment]
closed from #249
