### ISSUE TITLE
Forum / Moderation mode returns Internal Server Error

### ISSUE THREAD

**Issue by dstepp** [USStateDept/FPA_Core#247]
http://finddev.edip-maps.net/forum/forum/1-test/edit

**Comment by brandtheisey** [comment]
What user were you logged in as?

**Comment by nathanhilbert** [comment]
I didn't quite get to all of the moderation section.  There shouldn't be too much effort here though.

**Comment by dstepp** [comment]
admin@state.gov

**Comment by nathanhilbert** [comment]
closed from #249
