### ISSUE TITLE
Explore Converting Highcharts to D3

### ISSUE THREAD

**Issue by brandtheisey** [USStateDept/FPA_Core#253]
Switch from using Highcharts to D3 (or other team voted on **free** charting library).

Reason:  D3\* is free, highcharts is not for this project. Also, fundamentally, the charting functionality needs to be refactored so when that happens would be the right time to switch the the new **free** library.

This is a big lift so this issue is for tracking progress which will be done incrementally over time (in general order of the below list).
- [ ] Render Bar Charts in D3*
- [ ] Render Line in D3*
- [ ] Render Scatter in D3*
- [ ] Render Bubble in D3*
- [ ] General charting code to be more modular and reusable
- [ ] Remove Highcharts

We are open to any **free** charting library, D3 seems like it has the most options, but if another **free** library is comparable we'll use it.

**Comment by wiseguy** [comment]
Under Creative Commons license highcharts is free. http://shop.highsoft.com/highcharts.html

**Comment by brandtheisey** [comment]
It is explicitly not free for government use.

**Comment by dstepp** [comment]
![capture](https://cloud.githubusercontent.com/assets/5739648/9198830/d255022a-400c-11e5-81f6-36c21f9c421b.PNG)

**Comment by wiseguy** [comment]
Initially it was decided to buy it if we had to but if there is enough bandwidth and time to build it in d3 then it's not a bad idea

**Comment by nathanhilbert** [comment]
IMHO, a one-time $90 is nominal for the purchase of highcharts given the
scope of this project.  But, I agree with @davidstepp saying  "The two main
reasons, we need to refactor the util.js regardless, and D3 has greater
support".
With D3 in mind, there are a lot of available options that build on top of
D3.
- dc.js http://dc-js.github.io/dc.js/
- raw http://app.raw.densitydesign.org/#%2F -- downstream work
  https://github.com/USStateDept/Raw_Visualization for multiple charts on one
  page and automatic loading from FPA site
- Bokeh
  http://bokeh.pydata.org/en/latest/docs/installation.html#bokehjs-standalone
  -- useful to rendering static and dynamic JS visualizations.  I'm not sure
  how extendable it is though.  It uses canvas over SVG.  It is not built on
  top of D3, but has strong dev support
- Recline http://okfnlabs.org/recline/demos/ (Open Knowledge Foundation
  folks) -- a better example here
  https://spendb-dev.herokuapp.com/datasets/md-tenders (SpenDB is the
  downstream from openspending, which FIND is based on - FIND and SpenDB
  forked at different strategies around data loading)

**Comment by wiseguy** [comment]
In the scope of what FIND requires Highcharts would suffice. D3 as an API is more popular. Amongst non D3, highcharts is a very popular  library with a well documented API. It comes down to what the developers are more comfortable with versus having an interest in learning.

**Comment by dstepp** [comment]
The price is $3,000 not $90. And this also has to do with what additional visualizations F wants in the coming months. Let's table this discussion for a while.
