### ISSUE TITLE
As a user, I would like a choropleth map when multiple countries are selected.

### ISSUE THREAD

**Issue by leroybryant** [USStateDept/FPA_Core#255]

**Comment by dstepp** [comment]
Chloropleth does not work. See below.

http://finddev.edip-maps.net/data-visualization#f=1990|2014&i=gdp_per_capita_ppp&c=map&r=angola|armenia|australia|united kingdom|united states of america|united arab emirates|brazil|canada|dominican republic

**Comment by dstepp** [comment]
![image](https://cloud.githubusercontent.com/assets/5739648/9409189/7ce9a232-47e6-11e5-8a6f-84ba7b1bdf26.png)

**Comment by wiseguy** [comment]
Can you share the URL so I can recreate.

**Comment by dstepp** [comment]
Updated my previous comment with it.

**Comment by wiseguy** [comment]
Move the time slider to a year less than 2014. There seems to be no data for that year. I will add the gray as "No Data" to the legend for now.

**Comment by dstepp** [comment]
Okay, I got it to work on some years but when I check the Chart to see what years have data - it craps the bed.

**Comment by wiseguy** [comment]
line worked for me. x axis has as issue though showing fractions for years. data table is useful to see where data is missing.
http://finddev.edip-maps.net/data-visualization#f=2010|2010&i=gdp_per_capita_ppp&c=line&r=angola|armenia|australia|united+kingdom|united+states+of+america|united+arab+emirates|brazil|canada|dominican+republic

**Comment by dstepp** [comment]
I think this comment was meant for another issue. Not sure why their are partial years though....
