### ISSUE TITLE
As a user, I want units on the y and x axis

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#266]
Display units on the visualization.

**Comment by aminvafa** [comment]
Acceptance criteria: the units display when you download a visualization.

**Comment by dstepp** [comment]
@leroybryant will provide you with the field you need to fill out in order for us to display the units.

**Comment by leroybryant** [comment]
It is in the Admin section-> Indicators -> Sources.  Edit one of the indicators and it is the Units field.

**Comment by leroybryant** [comment]
The code to display the units on x and y is working.   The units just have to be entered into the database for them to be displayed.
