### ISSUE TITLE
As a user, I would like second level accrediting of sources on visualizations

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#267]
The World Bank compiiles indicators from multiple sources. We want to display the original source data instead of the aggregator.

**Comment by ghost** [comment]
Is the World Bank the only aggregator to which this is applicable? Or should we look at all aggregated sources?

**Comment by aminvafa** [comment]
All aggregated sources. World Bank was just the most important example because that's where the bulk of the data come from, and it has a robust API with Original Source listed.
