### ISSUE TITLE
As a user, I wouldn't like the units to display if they are null

### ISSUE THREAD

**Issue by leroybryant** [USStateDept/FPA_Core#279]
Units that have not been entered by F in Admin section-> Indicators -> Sources-> Units field will display as blank instead of (null).

**Comment by leroybryant** [comment]
Units that have not been entered by F in

**Comment by fucc1** [comment]
Didn't see the F required tag, but does your team need input from us?

**Comment by leroybryant** [comment]
Yes, the units would need to be entered for the indicators.
