### ISSUE TITLE
As a user, I would like the internal 500 error when building visualization resolved

### ISSUE THREAD

**Issue by leroybryant** [USStateDept/FPA_Core#282]
http://localhost:5000/api/slicer/cube/geometry/cubes_aggregate?&cluster=jenks&numclusters=4&cubes=access_to_credit_strength_of_l&cut=geometry__time:1990-2015&order=time&drilldown=geometry__country_level0@name|geometry__time&cut=geometry__country_level0@name:australia

ValueError: Fewer unique values than specified classes.

**Comment by nathanhilbert** [comment]
This should be taken care of here https://github.com/USStateDept/FPA_Core/blob/master/openspending/lib/cubes_util.py#L40.   Maybe the return is zero non-null values, in which case this logic wouldn't work.
