### ISSUE TITLE
Choropleth does not work when selecting regions.

### ISSUE THREAD

**Issue by dstepp** [USStateDept/FPA_Core#294]

**Comment by leroybryant** [comment]
@aminvafa We need to speak about the cases for multiple regions to close this out today.  One region works.

**Comment by backnotprop** [comment]
Ill work on implementing that this morning

**Comment by leroybryant** [comment]
The first selected region is displayed on the choropleth.  In the next sprint, we can discuss the cases of selecting multiple regions and regions and countries.
