### ISSUE TITLE
As a user, I would like API calls to work all of the time

### ISSUE THREAD

**Issue by nathanhilbert** [USStateDept/FPA_Core#305]
This is related to the intermittent 500 error received when a user is building a visualization.

**Tech stuff**
The many simultaneous calls concurrently to the database might be the cause of the error as connection queuing pools are hit. 
This error can be recreated by replicating the Apache server on a dev machine, and running a siege test using 

```
$ siege -c50 -d1 -v -i -f urllist.txt
```

where urllist is [this file](https://gist.github.com/nathanhilbert/8187132fc81fd735828e)

A few thoughts:
- [x] ~~Check that the cubes slicer application is tearing down the DB connections upon completion of it's work~~ we don't actually go through the slicer blueprint, but rather use parts of cubes programmatically.
- [x] **Check that connection pool limits for the database/SQLAlchemy are appropriately set** see findings below.
- [x] ~~Check Apache keepalives and connection limits in mpm confs~~, KeepAlive should be kept off for Flask applications.
- [x] Use the Status module in apache to better monitor server connections
- [x] ~~Dig deeper into the actual error in the cubes software of cannot find the star_cube.~~ I think there were some client-side caching for this see thoughts below.

**Comment by nathanhilbert** [comment]
Thoughts for review for front-end improvement.
- [ ] Do not call the cluster param if it not needed (all visualizations except the map).  It isn't extreme computation, but useless if it is not used.

Thoughts for the back-end.
- [x] Caching should be set up when the javascript and API are in a stable state (not many more edits).  Any repeated calls from the front-end, would return a cached response and would not have to hit the database at all, which seems to be our primary bottleneck. see #307
- [x] Dig deeper into the cache timeouts on the client side for AJAX calls.  certain headers and methods can quickly expire calls until the front-end and back-end are out of Beta. See #306

**Comment by dstepp** [comment]
I think these are all really great comments. Thanks for looking into the performance issues.

**Comment by nathanhilbert** [comment]
Findings (not a pun)
- SQLAlchemy uses default connections pooling numbers (5) with a overflow max of 10.  For the find system, these should be substantially higher to the tune of 50 and 200.  To address this, see https://github.com/USStateDept/FPA_Core/commit/46afec21b82cdb7ac902c9fde4a667cec58c71d7
- With the fix above, we now hit the postgres connection limit which is defaulted to 100 on vanilla installs on the dev machines; however, on the AWS RDS Postgres the connection limit size is around 6000.

**Comment by nathanhilbert** [comment]
With the fixes above to the pool limits and postgres max connection, siege is showing the results below.  Translation is with 50 concurrent users, we have a max response time of 24 seconds, which is pretty abysmal.  This can be improved with server-side caching, since there will be a lot of common calls.  But, related to this issue, there were no 500 responses.

```
$ siege -c50 -d5 -v -i -f ~/usdept/siege/urllist.txt
Transactions:                 99 hits
Availability:              93.40 %
Elapsed time:              45.66 secs
Data transferred:           0.10 MB
Response time:             12.22 secs
Transaction rate:           2.17 trans/sec
Throughput:             0.00 MB/sec
Concurrency:               26.50
Successful transactions:          99
Failed transactions:               7
Longest transaction:           24.78
Shortest transaction:           1.21

```

**Comment by nathanhilbert** [comment]
w/ caching of the API slicer calls
Transactions:		         194 hits
Availability:		      100.00 %
Elapsed time:		       60.47 secs
Data transferred:	       22.97 MB
Response time:		       10.80 secs
Transaction rate:	        3.21 trans/sec
Throughput:		        0.38 MB/sec
Concurrency:		       34.63
Successful transactions:         194
Failed transactions:	           0
Longest transaction:	       34.63
Shortest transaction:	        0.00


w/o caching:
Transactions:		          62 hits
Availability:		       60.78 %
Elapsed time:		       60.85 secs
Data transferred:	        0.05 MB
Response time:		       14.01 secs
Transaction rate:	        1.02 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		       14.27
Successful transactions:          62
Failed transactions:	          40
Longest transaction:	       29.88
Shortest transaction:	        0.00

**Comment by nathanhilbert** [comment]
The back-end issue is threading and the way that cubes handles database connections.
The problem can be recreated by running the following, then doing a benchmark test on any URLs that have slicer in them 

```
$ ostool runserver --threaded
```

If the server is run as below without the threaded, then the incoming connections are non-concurrent, so the database connections will not collide. 

```
$ ostool runserver
```

Apache is a threaded server when served through Windows (whereas Linux uses a process workers).  I'm guessing cubes has never been benchmarked in a threaded environment.  Looking into solutions thinking of one of the follow:
- [X] reuse the connection from the openspending application - Doesn't make a difference
- [X] Increase connectionpool number - doesn't make a different and this error happens in the first connections, then is fine.
- [X] Look at sqlalchemy connection pool classes - tried all of them with no difference, and some worse.
- [X] Try is dispose or clean up any connections from the openspendingstore exposed to cubes
- [X] ~~Maybe change db.engine.execute to db.session.execute (in order to use the thread scoped session)~~ - no improvement
- [X] ~~declare a fresh cubes workspace for every connection to an API route~~ - no improvement
- [ ] Force the store to create a new connection when workspace is loaded?
- [ ] ~~See if running on linux makes a different.  Running the application as a process should isolate the db connections.~~ - Way too much overhead
- [ ] Since we are working with a set schema of data, we could probably just rewrite the API backend for slicer to database queries.  We would lose some functionality and flexibility that isn't being used with this direction.

**Comment by mdramos** [comment]
There is talk of a possible rewrite in Node.js. What do you think about this Nathan?

**Comment by nathanhilbert** [comment]
This issue should be fixed with https://github.com/USStateDept/cubes/pull/1
