### ISSUE TITLE
Set up server-side caching on the server in order to reduce response time.

### ISSUE THREAD

**Issue by nathanhilbert** [USStateDept/FPA_Core#307]
Caching should be set up when the javascript and API are in a stable state (not many more edits). Any repeated calls from the front-end, would return a cached response and would not have to hit the database at all, which seems to be our primary bottleneck.

**Comment by dstepp** [comment]
We are only running on a medium class, would uping the class improve performance?

**Comment by nathanhilbert** [comment]
I didn't specify the metrics of bottleneck.  I was only talking about response time per call.  Increasing the class size would allow more concurrent connections, but I don't think it would impact the response time.  Let's see what kind of resources are used with the new connection pool settings.

**Comment by nathanhilbert** [comment]
w/ caching of the API slicer calls

```
Transactions:                194 hits
Availability:             100.00 %
Elapsed time:              60.47 secs
Data transferred:          22.97 MB
Response time:             10.80 secs
Transaction rate:           3.21 trans/sec
Throughput:             0.38 MB/sec
Concurrency:               34.63
Successful transactions:         194
Failed transactions:               0
Longest transaction:           34.63
Shortest transaction:           0.00
```

w/o caching:

```
Transactions:                 62 hits
Availability:              60.78 %
Elapsed time:              60.85 secs
Data transferred:           0.05 MB
Response time:             14.01 secs
Transaction rate:           1.02 trans/sec
Throughput:             0.00 MB/sec
Concurrency:               14.27
Successful transactions:          62
Failed transactions:              40
Longest transaction:           29.88
Shortest transaction:           0.00
```

**Comment by nathanhilbert** [comment]
was done with #332
