### ISSUE TITLE
HTML code visible when signing up for USG login access

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#315]
Sign up function works fine, but HTML code was visible. Not urgent, but just noting it. (Windows 7; Google Chrome browser)
![beta email signup bug](https://cloud.githubusercontent.com/assets/10505111/9661729/13410c96-522a-11e5-87c9-936165c22df4.png)

**Comment by nathanhilbert** [comment]
relates to #248 
Once we have an email server, this will be sent via email only, and the user would see a message saying check your email.  Suggesting to close as duplicate.

**Comment by nathanhilbert** [comment]
closed with https://github.com/USStateDept/FPA_Core/commit/f3fec305073d99750b228618aaacd98930b9cee8
