### ISSUE TITLE
As a site admin, I'd like to be able to create Data Collections

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#317]
I don't know where to denote which indicators belong in which data collection.

**Comment by aminvafa** [comment]
How do we do this?

**Comment by jonvan5** [comment]
see #387 for a list of Data Collection group names.

**Comment by leroybryant** [comment]
I created a new tag category.  If you tag an indicator with one of the collection names you stated in #387, it will appear in that collection group.
