### ISSUE TITLE
Speed up the API calls

### ISSUE THREAD

**Issue by nathanhilbert** [USStateDept/FPA_Core#328]
- [x] Bind to selected tables use sqlalchemy or maybe Blaze and reduce
- [x] Heavy backend caching for APIs
- [ ] make cache dirty for updates of data

**Comment by nathanhilbert** [comment]
Baseline siege -c50 -i -t60s -v -b -f urllist_speedup.txt
Transactions:                229 hits
Availability:             100.00 %
Elapsed time:              59.47 secs
Data transferred:           3.41 MB
Response time:             11.43 secs
Transaction rate:           3.85 trans/sec
Throughput:             0.06 MB/sec
Concurrency:               44.03
Successful transactions:         229
Failed transactions:               0
Longest transaction:           18.90
Shortest transaction:           0.68

**Comment by brandtheisey** [comment]
This is Fs current #1 priority as 9/14/15.

**Comment by nathanhilbert** [comment]
Thanks.  On it.  I think the "F Required" tag is to indicate to F that information is needed.  Inherently, all issues are required by F, right?

**Comment by nathanhilbert** [comment]
With caching of 20 different calls. Indicates 300% improvement.  Still 17 seconds is too long for the longest transaction.
Transactions:                715 hits
Availability:              98.62 %
Elapsed time:              59.17 secs
Data transferred:           7.91 MB
Response time:              3.34 secs
Transaction rate:          12.08 trans/sec
Throughput:             0.13 MB/sec
Concurrency:               40.40
Successful transactions:         715
Failed transactions:              10
Longest transaction:           17.42
Shortest transaction:           0.52

**Comment by brandtheisey** [comment]
Good point. I had added it for the purposes of a meeting I just had but you are correct.

**Comment by nathanhilbert** [comment]
New API without caching.
Transactions:                298 hits
Availability:             100.00 %
Elapsed time:              59.96 secs
Data transferred:           8.83 MB
Response time:              8.89 secs
Transaction rate:           4.97 trans/sec
Throughput:             0.15 MB/sec
Concurrency:               44.20
Successful transactions:         298
Failed transactions:               0
Longest transaction:           17.34
Shortest transaction:           0.00

**Comment by nathanhilbert** [comment]
New API with caching and full features
Transactions:                480 hits
Availability:              96.97 %
Elapsed time:              59.90 secs
Data transferred:           1.85 MB
Response time:              4.36 secs
Transaction rate:           8.01 trans/sec
Throughput:             0.03 MB/sec
Concurrency:               34.92
Successful transactions:         480
Failed transactions:              15
Longest transaction:           23.68
Shortest transaction:           1.17

**Comment by nathanhilbert** [comment]
closed with #332
