### ISSUE TITLE
Choosing El Salvador displays data for all countries starting with El Salvador through the end of the alphabet

### ISSUE THREAD

**Issue by ghost** [USStateDept/FPA_Core#333]

**Comment by ghost** [comment]
http://find.state.gov/data-visualization#f=1990|2014&i=access_to_credit_strength_of_l&c=line&r=el-salvador

**Comment by nathanhilbert** [comment]
The name el salvador shouldn't have a hyphen in it.  The API resolves this
to mean get all data between el and salvador.  This API gets the correct
data
http://find.state.gov/api/slicer/cube/geometry/cubes_aggregate?&cluster=jenks&numclusters=4&cubes=access_to_credit_strength_of_l&cut=geometry__time:1990-2015&order=time&drilldown=geometry__country_level0@name|geometry__time&cut=geometry__country_level0@name:el%20salvador

**Comment by ghost** [comment]
I stand corrected.
