### ISSUE TITLE
On the data tab, clicking Collections nothing shows up

### ISSUE THREAD

**Issue by dstepp** [USStateDept/FPA_Core#342]

**Comment by backnotprop** [comment]
This is working for me on my dev machine, with the latest commit. Has this issue been resolved or is it a production bug?

**Comment by dstepp** [comment]
This is from production.

**Comment by aminvafa** [comment]
I wanted to flag #317 here. How do we create a collection and add indicators to them?

**Comment by jonvan5** [comment]
see #387 for a list of Data Collection group names.
