### ISSUE TITLE
Add banner to beta site

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#344]
Banner text: "FIND is still in the early stages of development. If you see any bugs or data errors while using the site, please share them with us using our feedback form on the right."

**Comment by aminvafa** [comment]
I see this is closed now. Has it been pushed yet?

**Comment by leroybryant** [comment]
No, it hasn't yet.  We can if you'd like it up soon.

**Comment by aminvafa** [comment]
Yes. Please push the banner live.

**Comment by aminvafa** [comment]
OK, so I see banner on the home page. Is it possible for it  to be available on every page? See an example on http://beta.foreignassistance.gov/

**Comment by ghost** [comment]
If we want the banner on every page , we can just put it into the base.jade file. But then we run into a challenge where, if a user x's out the banner and then navigates to a different page (i.e. from home to /visualization), the banner pops up again. I know Angular has a directive for this sort of thing  and I would imagine Knockout does too. I am looking into this right now.

**Comment by aminvafa** [comment]
OK let us know what you find out. It'd be nice if the banner also didn't create all that extra white space behind it, too.
