### ISSUE TITLE
As a user, I would like all data points connected on a LINE GRAPH

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#347]
Currently, only continuous points are connected on a line graph. We want all points to be connected and there to only be a line marker where there's a value.

**Comment by jonvan5** [comment]
This may be fixed now.

**Comment by ghost** [comment]
Can you please send a specific example where it's not working?

**Comment by aminvafa** [comment]
This is all set. Please mark it as done.
