### ISSUE TITLE
Generate Source Report and Indicator Report

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#349]
We want a rack up of all the data that are in the system so we know how many indicators we have, their sources (and secondary sources), and how often they're updated. We have attached templates with dummy placeholder data. 

Some of the information (such as update frequency) may not readily be available, and that information can fall on F/PA to update. The rest should be available as metadata within the system.

We have assigned this to Open Beta, but we would like this sooner than that (the next sprint review, preferably).

[Sources Report_TEMPLATE.xlsx](https://github.com/USStateDept/FPA_Core/files/5412/Sources.Report_TEMPLATE.xlsx)

**Comment by nathanhilbert** [comment]
This is largely accomplished with http://find.state.gov/admin/qaview/ with much more information.  A single report will be generated using the template above.

**Comment by leroybryant** [comment]
@aminvafa , does the qaview suffice?

**Comment by aminvafa** [comment]
We can see that the info we asked for in the template is available once you dig down into that page, but is it possible for us to generate a report (that looks like our template) since all of the information is available?

**Comment by leroybryant** [comment]
Sure, I will look into it.
