### ISSUE TITLE
As a user, I would like to close a category tile by clicking out of the tile.

### ISSUE THREAD

**Issue by jonvan5** [USStateDept/FPA_Core#350]
Currently, when choosing indicators through the category tiles (e.g. Economic Growth) users need to click the top of a selected tile. Clicking outside the tile should also close it out.

**Comment by backnotprop** [comment]
@jonvan5 would you be ok with us making this category "card"/window act like the "Edit Visualiztion" modal where it just pops out, as opposed to the card-flipping animation?

**Comment by aminvafa** [comment]
Yes. Some users have also noted that when the tile flips over to the pop-up, they get a pop-up that's sized to their screen resolution, and that can mean a really gigantic pop-up.

**Comment by aminvafa** [comment]
Make sure this feature is enabled on the Build-a-viz page and the Categories page
