### ISSUE TITLE
Incorrect text displays when resetting password

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#352]
The password reset functionality for the USG user login works great. However, there's a small bug in the display title. It says "This operation is not possible for this user type." The second line about the password reset working is good, so maybe just delete the previous line.
![password reset screen](https://cloud.githubusercontent.com/assets/10505111/10248529/1e4793be-68ee-11e5-8aea-b6f6b4c8eabf.PNG)

**Comment by nathanhilbert** [comment]
That's a security measure for admin user accounts.  Admins cannot request a password reset.

**Comment by aminvafa** [comment]
Ah. Well I'm an admin, I forgot my password, I requested a reset, and I got one. Maybe something else needs to be fixed?

**Comment by leroybryant** [comment]
@aminvafa You're right.  I just tested it with my admin account and got the same results.    I will open a new ticket.
