### ISSUE TITLE
Maps should not load on 2014

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#355]
Most indicators don't have data for 2014. When maps are automatically loaded, they default to 2014, but since there's likely no data, it looks like the map is broken. 

Make default year for maps latest year available for the dataset. Or universally set 2012 or 2013 as default year.

**Comment by leroybryant** [comment]
@aminvafa is this only for maps?

**Comment by aminvafa** [comment]
Any viz that only shows one year at a time (so maps, bar charts, and bubble charts as of now) likely have this issue.

And it's not that we never want 2014 displayed, but when 2014 is the default year of display, the visualization looks wrong because most sources have the latest year of data available as earlier than 2014.

**Comment by leroybryant** [comment]
So you want the default year to be 2013, but for them to be able to scroll to 2014 for maps, bar chart, and bubble.  Is that correct?
