### ISSUE TITLE
As a user, I would like to see data values when hovering over a country on a map

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#362]
Currently you see the name, but you have to click to get the value. 

Eliminate hovering to see the name, and eliminate clicking to see the name+value. And just have hovering to see name+value.

**Comment by leroybryant** [comment]
If the country is selected and has data, the value is shown.   If it selected and has no data, "No Data" is shown.  If it is a country that isn't selected, only the name shows.
