### ISSUE TITLE
Edit map footer

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#367]
Eliminate “Additionally, subnational boundaries may appear even though no subnational data are available in FIND. If you select a subnational area, you will be shown national information.” from the data viz footer. 

Also, make this footer only appear on map pages.

**Comment by leroybryant** [comment]
It shouldn't say, "For more information about the geography tile layer, visit openstreetmap.org." either.   A previous layer had that as a source.  The current layer was created by us.  I'll take that out as well until  you determine what you'd like it to say.

**Comment by aminvafa** [comment]
That sounds good, @leroybryant. Just keeping the first line is sufficient (and making it only appear on maps and not all types of visualizations).
