### ISSUE TITLE
Line graph shouldn't combine indicators

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#373]
Somehow this chart is producing two indicators and combining them. This shouldn't happen.

http://find.state.gov/data-visualization#f=2004|2014&i=access_to_credit_strength_of_l|access_to_land&c=line&r=dos_region:all|algeria|azerbaijan

**Comment by ghost** [comment]
How did this issue present itself? 
Was it through the build-a-visualization process?
If so, what were the actions made by the user immediately preceding the error?
If not,  was it by way of changing the URL?
Either way, it needs to be fixed.
Your answers will help trace the problem.

Thank you..

**Comment by aminvafa** [comment]
OK, I called the user to figure it out. We retraced, and here's how it happened.

Build-a-viz the normal way.
Edit visualization.
Click on an indicator. If you click on just one, you can swap. BUT there's nothing stopping you from clicking on multiple indicators, including the same indicator over and over. I clicked on "access to electricity" numerous times, and at some point it started counting by 2s (so 20, 22, 24, 26 indicators). And when I clicked "Swap," it gave me the URL: http://find.state.gov/data-visualization#f=2004|2014&i=access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity|access_to_electricity&c=line&r=dos_region:all
