### ISSUE TITLE
Maps can't chart "all regions"

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#383]
Tried to do a visualization of all DOS regions, and it failed. All I can see is just a floating shapefile of Afghanistan like in #381

http://find.state.gov/data-visualization#f=2013|2013&i=population&c=map&r=dos_region:all

**Comment by leroybryant** [comment]
The commit I did for #381 about edit visualization fixes this.  The coloring #354 and years #355 have to be fixed.
