### ISSUE TITLE
Forest Area data invalid

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#386]
http://find.state.gov/data-visualization#f=1990|2014&i=forest_area&c=line&r=dos_region:all

Data unit is % of land area, but the y-axis and data label values are clearly not percents

**Comment by leroybryant** [comment]
I will make part of the admin section editable so you can edit units

**Comment by aminvafa** [comment]
My concern is also that the incorrect data is being pulled in. If you look at the World Bank source URL, it's pulling from a page that has % as the units, too. So I don't know where the numbers in FIND are coming from.

**Comment by leroybryant** [comment]
It is coming from a field in the database that is mostly empty.  We put in preliminary values.     That "% of land area" was input by someone on the  databank site.

**Comment by leroybryant** [comment]
If you go to the admin section->Reports-> Indicators, you can see which are empty.  I have made it editable so the fields can be filled in.
