### ISSUE TITLE
Data Collection groups

### ISSUE THREAD

**Issue by jonvan5** [USStateDept/FPA_Core#387]
Data Collections should include the following groups:
• CDA – Country Data Analytics
• DHS – Demographic and Health Surveys
• MCC – Millennium Challenge Corporation
• IMF - International Monetary Fund 
• SDGs  - Sustainable Development Goals 
• UIS  - UNESCO Institute for Statistics 
• WHO – World Health Organization

F can assign indicators to the appropriate groups when these are available.

**Comment by leroybryant** [comment]
I created a new tag category.  If you tag an indicator with one of these collection names , it will appear in that collection group.

**Comment by aminvafa** [comment]
Great! Are these accessible yet? I went to http://find.state.gov/admin/tagbyindicator/ and selected an indicator, but the collections above weren't available in the list. Am I in the wrong place?

**Comment by aminvafa** [comment]
Will the Collection tags be available in the next push? Also, when is the next push?

**Comment by dstepp** [comment]
Next push is tomorrow (every Friday before the Sprint review). We've been working on configuring the Testing servers and reducing the complexity of Production as well. This issue will be in the next push.

**Comment by aminvafa** [comment]
Gotcha. Thanks @dstepp
