### ISSUE TITLE
Put IE warnings in templates

### ISSUE THREAD

**Issue by nathanhilbert** [USStateDept/FPA_Core#48]
ie10-viewport-bug-workaround.js
and ie8 file warning.js

**Comment by dstepp** [comment]
Do we need to still work on this? Looking into the repo, it looks like some of the code is still commented out: https://github.com/USStateDept/FPA_Core/blob/69de501b833d904254c3b494c91c268e126306c9/openspending/templates/includes/head.jade

**Comment by dstepp** [comment]
Closing this issue. By the time we go to production, all of DoS will be moved to IE11.
