### ISSUE TITLE
Compile JS using gulp

### ISSUE THREAD

**Issue by nathanhilbert** [USStateDept/FPA_Core#72]

**Comment by nathanhilbert** [comment]
Curious why this was reverted (https://github.com/USStateDept/FPA_Core/commit/78f6a49bf52e4a4476a8855941bb05eba7a601c1).  changing system settings to ASSETS_DEBUG=True would be the equivalent of the revert that prints outs all of the js. (http://flask-assets.readthedocs.org/en/latest/).  If there was another issue, please open a ticket.

**Comment by dstepp** [comment]
@wiseguy any reason on the revert?

**Comment by wiseguy** [comment]
We were hitting the MVP deadline and the easiest thing to do was to revert it. It can be brought back since it sounds like a small task

**Comment by dstepp** [comment]
@Nathanhilbert what's the update on this?

**Comment by nathanhilbert** [comment]
It will take about 30 minutes to plug back in.  I'll be sure to send instructions for everyone as well.

**Comment by nathanhilbert** [comment]
The JS is failing after running through jsmin.  I'll have to look into this deeper.

**Comment by nathanhilbert** [comment]
We may want to hold on this until the JS refactor takes place opposed to adding complexity for the deployment, then reverting to something else in the future.  There are a number of ways to compile and minify JS and CSS using tools like requirejs, gulp(currently used, but without minifying js), and python tools like flask-assets.  Thoughts?

**Comment by backnotprop** [comment]
For minifying I think it would be best to use a JS task-runner such as Gulp. Incorporating requireJS would be nice down the road as the codebase grows.

**Comment by nathanhilbert** [comment]
closed with #326
