### ISSUE TITLE
Add whitelisted domains to settings for user emails

### ISSUE THREAD

**Issue by nathanhilbert** [USStateDept/FPA_Core#98]
https://trello.com/c/xL5CLRzV/9-implement-user-authentication-system-with-email-verification-to-whitelisted-domains

**Comment by dstepp** [comment]
Who are we getting the domains from?

**Comment by dstepp** [comment]
@nathanhilbert bump

**Comment by nathanhilbert** [comment]
Should be provided by F.  Could be in the form whitehouse.gov, usaid.gov, state.gov or *.gov for all government sites.

**Comment by aminvafa** [comment]
Here's the list to start:
census.gov
usmc.mil
mcc.gov
state.gov
usaid.gov
usda.gov
usgs.gov

How easy/difficult is it to add more domains later?

**Comment by nathanhilbert** [comment]
It is very easy to update this list, but it would be easier for us if it were in bulk changes opposed to adding one or removing one here and there.  Thanks.

**Comment by nathanhilbert** [comment]
@brandtheisey Can you add these to the server settings.py file?  The structure is in the template (https://github.com/USStateDept/FPA_Core/blob/master/settings.py_tmpl#L56).
